# Generated by Django 5.2.6 on 2025-09-27 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturasItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilhete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fatura_item', to='ficha3.bilhete')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ficha3.fatura')),
            ],
            options={
                'verbose_name': 'Item da Fatura',
                'verbose_name_plural': 'Itens da Fatura',
            },
        ),
    ]
